#!/bin/bash
# -----------------------------------------------------------------------
#  This script causes Linux to scan the PCI bus for the specified
#  PCI device(s) and enable BustMaster mode
#
#  This script must be run with root privileges!  Use sudo.
#
#  Author: Doug Wolf
# ----------------------------------------------------------------------

# Ensure that we're running with root privileges
if [ $(id -u) -ne 0 ]; then
    sudo $0 $1 $2 $3 $4  $5 $6
    exit $?
fi


enable_bus_master()
{
    local device=$1

    # Look up the BDF that corresponds to this device id
    line=$(lspci -d $device)
    if [ -z "$line" ]; then
        echo "=========================================="
        echo "  bus_master: device $device not found"
        echo "=========================================="        
        return
    fi  
    line=($line)
    bdf=${line[0]}

    # Turn on BusMaster mode for this device
    echo "Enabling BusMaster mode on ${device} at BDF ${bdf}"
    setpci -s $bdf COMMAND=0106
}

# Start with an empty array of device IDs
array=()

# If there are no devices on the command line, use
# lspci to go find some 
if [ $# -ne 0 ]; then
    array=($1 $2 $3 $4 $5 $6)
else
    filename="/tmp/${RANDOM}.tmp"
    lspci -n | grep "10ee:" > $filename
    while read line; do
       words=($line)
       device=${words[2]}
       array+=($device)
    done  < $filename
    rm -rf $filename
fi

# If we didn't find any devices, complain
if [ ${#array[@]} -eq -0 ]; then
   echo "bus_master: no devices listed on command line or found via lspci"
   exit 1
fi

# Now go enable bus-master mode on each device
for device in ${array[@]}; do
    enable_bus_master $device
done
